baseURL: https://aafu.pages.dev/
languageCode: en-us
build:
  writeStats: true
theme: ["hugo-embed-pdf-shortcode"]
enableInlineShortcodes: true
params:
  title: aafu theme
  author: Maier Jonas
  description: Portfolio Maier
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Github](https://github.com)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Jonas Maier"
    tagline: Schüler
    location: "5723 Uttendorf"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-stack-overflow
        url: "https://stackoverflow.com/users/20582393/nasgur"
        title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/huthuthiddeli"
        title: GitHub
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Enthusiastischer Schüler der HTL-Saalfelden mit unbeschreiblichen Elan und Interesse.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Praktikum
        dates: 2018
        company: Kitzsteinhorn
        details: |1-
          - Sensoren in Kartenscannern gewechselt.
          - Neue PCs aufgesetzt.
          - Arbeiten in der Elektrowerktatt.
          - Server-Client Applikation für Fotoautomat programmiert.
  education:
    title: Ausbildung
    icon: fas fa-graduation-cap
    list:
      - degree:
        college: Mittelschule
        dates: 2012 - 2017
        thesis_title: Schwerpunkt Mathe
        thesis_url: "https://www.ms-uttendorf.salzburg.at/"
      - degree: Matura
        college: HTL-Saalfelden
        dates: 2018 - 2025
        thesis_url: "#"
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: SYP-Projekt 2022/23
        description: Kleines Videospiel mit Website und Datenbank
        url: "https://github.com/huthuthiddeli/SYP_Projekt_2022-23"
      - title: SYP-Projekt 2023/24
        description: Fernsteuerung eines M-Bots
        url: "https://github.com/huthuthiddeli/SYP_PROJEKT_23-24_Maier"
      - title: DermAI
        description: Applikation zur früherkennung von Hautkrebs
      - title: Pferderennen POS 2024
        description: Kleines Pferderennen mit Backend crossplatform 
        url: "https://github.com/huthuthiddeli/SYP_PROJEKT_23-24_Maier"
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Chillei
        skillrating: 69
      - skill: Fehlstundenquote 
        skillrating: 100
      - skill: Schule
        skillrating: 0
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Computerspielen
      - hobby: Autofahren
      - hobby: Über das Leben philosophieren


