name: Continous Integration and Deployement

on:
  push:
    branches:
        - main


env:
  NODE_VERSION: '20.10.0'

jobs:
  build:
    runs-on:ubuntu-latest
    environment: Azure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node 
        uses: actions/setup-node@v4
        with:
          dotnet-version: ${{ env.NODE_VERSION }}